In [2]:
import numpy as np
import pandas as pd

#Read Data
from google.colab import files
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
# Q1 --> Loading the dataset
bac = pd.read_csv('/content/drive/My Drive/Colab Notebooks/blogtext.csv')

In [91]:
bac_df=bac[:2000]
bac_df.head(2)

id  ...                                               text
0  2059027  ...             Info has been found (+/- 100 pages,...
1  2059027  ...             These are the team members:   Drewe...

[2 rows x 7 columns]

In [92]:
bac_df.shape

(2000, 7)

In [0]:
#Q2
# import and instantiate CountVectorizer (with the default parameters)
from sklearn.feature_extraction.text import CountVectorizer
cvect = CountVectorizer(stop_words='english',lowercase=True)
# Lowercase, stopwords have been forced. Unwanted spaces and characters are automatically removed unless included using token_pattern)

In [94]:
#Q3 
bac_df.dtypes

id         int64
gender    object
age        int64
topic     object
sign      object
date      object
text      object
dtype: object

In [95]:
bac_df['labels']=bac_df['gender']+bac_df['age'].astype(str)+bac_df['topic']+bac_df['sign']
bac_df.head(2)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


id  ...            labels
0  2059027  ...  male15StudentLeo
1  2059027  ...  male15StudentLeo

[2 rows x 8 columns]

In [96]:
bac_df1=bac_df.drop(['id','gender','age','topic','sign','date'],axis=1)
bac_df1.head(2)

text            labels
0             Info has been found (+/- 100 pages,...  male15StudentLeo
1             These are the team members:   Drewe...  male15StudentLeo

In [97]:
#Q4: Separating Features and Labels, train/test split 
x=bac_df1['text']
y=bac_df1['labels']
print(x.head(2))
print(y.head(2))

0               Info has been found (+/- 100 pages,...
1               These are the team members:   Drewe...
Name: text, dtype: object
0    male15StudentLeo
1    male15StudentLeo
Name: labels, dtype: object


In [0]:
from sklearn.model_selection import train_test_split

In [0]:
# split X and y into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(x, y,random_state=10)

In [100]:
##Training data
print(x_train.shape)
print(y_train.shape)

(1500,)
(1500,)


In [101]:
#Test data
print(x_test.shape)
print(y_test.shape)

(500,)
(500,)


In [102]:
#Q5 --> Vectorize the features
#Feed input data to CountVectorizer after including ngram
cvect = CountVectorizer(stop_words='english',lowercase=True,ngram_range=(1,2))
cvect.fit(x_train)

#Check the vocablury size
len(cvect.vocabulary_)


144631

In [0]:
#Convert Training/Test data Count Vectors
x_train_ct=cvect.transform(x_train)
x_test_ct=cvect.transform(x_test)

In [104]:
#Size of Document Term Matrix
print(x_train_ct.shape)
print(x_test_ct.shape)

(1500, 144631)
(500, 144631)


In [105]:
#sparse matrix
print(x_train_ct[0])

  (0, 175)	1
  (0, 184)	1
  (0, 1030)	1
  (0, 1037)	1
  (0, 1320)	1
  (0, 1332)	1
  (0, 1345)	1
  (0, 1346)	1
  (0, 7770)	1
  (0, 7788)	1
  (0, 23441)	1
  (0, 23443)	1
  (0, 59665)	1
  (0, 59688)	1
  (0, 59697)	1
  (0, 61219)	1
  (0, 61222)	1
  (0, 61658)	1
  (0, 61671)	1
  (0, 77077)	1
  (0, 77078)	1
  (0, 87446)	1
  (0, 87447)	1
  (0, 101395)	1
  (0, 101541)	1
  (0, 133341)	1
  (0, 133547)	1
  (0, 142855)	1
  (0, 142887)	1


In [106]:
#Q6: Printing the dictionary
y_train.value_counts()

male35TechnologyAries               441
female24indUnkScorpio               145
female15StudentLibra                105
male24EngineeringLibra               88
female27EducationAquarius            71
male17Sports-RecreationCapricorn     57
female15StudentAquarius              52
male33InvestmentBankingAquarius      50
male25Non-ProfitCancer               38
male23indUnkSagittarius              36
male14StudentScorpio                 34
female25StudentTaurus                28
male26indUnkLeo                      27
male39EducationVirgo                 25
male15StudentAquarius                24
female15indUnkAries                  21
male15ScienceLibra                   21
male17StudentSagittarius             20
male24BusinessServicesCancer         18
male25InternetAries                  17
female14indUnkAries                  16
female37indUnkAquarius               15
female23indUnkLibra                  14
female17StudentAries                 14
male23indUnkTaurus                   13


In [107]:
d=y_train.value_counts().to_dict()
d

{'female14indUnkAries': 16,
 'female14indUnkCancer': 3,
 'female14indUnkLeo': 4,
 'female15ArtsPisces': 2,
 'female15StudentAquarius': 52,
 'female15StudentCancer': 5,
 'female15StudentGemini': 3,
 'female15StudentLibra': 105,
 'female15indUnkAries': 21,
 'female16indUnkTaurus': 11,
 'female17StudentAries': 14,
 'female17StudentGemini': 7,
 'female23indUnkAquarius': 1,
 'female23indUnkLibra': 14,
 'female23indUnkVirgo': 2,
 'female24BankingLibra': 3,
 'female24indUnkScorpio': 145,
 'female25StudentTaurus': 28,
 'female25indUnkSagittarius': 1,
 'female25indUnkTaurus': 4,
 'female26AccountingAquarius': 1,
 'female26ScienceSagittarius': 2,
 'female27EducationAquarius': 71,
 'female33BankingAquarius': 11,
 'female33indUnkLeo': 6,
 'female33indUnkSagittarius': 1,
 'female34indUnkScorpio': 4,
 'female37indUnkAquarius': 15,
 'female45indUnkSagittarius': 9,
 'male14StudentScorpio': 34,
 'male15ScienceLibra': 21,
 'male15StudentAquarius': 24,
 'male15StudentLeo': 3,
 'male16indUnkGemini': 3,
 '

In [108]:
d['male35TechnologyAries']

441

In [0]:
#Q7 --> Transform the labels
from sklearn.preprocessing import MultiLabelBinarizer
mlb = MultiLabelBinarizer()



In [112]:
y_train1=mlb.fit_transform(y_train)
y_train1

array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 1, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 1, ..., 1, 0, 0],
       [0, 1, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]])

In [113]:
mlb.classes_

array(['-', '1', '2', '3', '4', '5', '6', '7', '9', 'A', 'B', 'C', 'E',
       'G', 'I', 'L', 'M', 'N', 'P', 'R', 'S', 'T', 'U', 'V', 'a', 'b',
       'c', 'd', 'e', 'f', 'g', 'h', 'i', 'k', 'l', 'm', 'n', 'o', 'p',
       'q', 'r', 's', 't', 'u', 'v', 'y'], dtype=object)

In [111]:
y_test1=mlb.fit_transform(y_test)
y_test1

array([[0, 1, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 1, ..., 1, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1]])

In [0]:
#Q8 - choosing a classifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn import linear_model
from sklearn.linear_model import LogisticRegression


In [0]:
clf=LogisticRegression(solver='lbfgs')
clf=OneVsRestClassifier (clf)


In [116]:
clf.fit(x_train_ct, y_train1)

/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label 24 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label 28 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label 34 is present in all training examples.
  str(classes[c]))
/usr/local/lib/python3.6/dist-packages/sklearn/multiclass.py:75: UserWarning: Label 35 is present in all training examples.
  str(classes[c]))


OneVsRestClassifier(estimator=LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=100,
                                                 multi_class='auto',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=None,
                                                 solver='lbfgs', tol=0.0001,
                                                 verbose=0, warm_start=False),
                    n_jobs=None)

In [0]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn import preprocessing
from sklearn.metrics import f1_score,classification_report, confusion_matrix,accuracy_score

In [0]:
#Q-9
y_predict = clf.predict(x_test_ct)



In [119]:
y_predict

array([[0, 1, 0, ..., 1, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1]])

In [0]:
y_predict1=mlb.inverse_transform(y_predict)

In [123]:
print(metrics.accuracy_score(y_test1, y_predict))

0.352


In [126]:
print(metrics.classification_report(y_test1, y_predict))

              precision    recall  f1-score   support

           0       0.92      0.34      0.50        32
           1       0.91      0.51      0.66       142
           2       0.71      0.52      0.60       146
           3       0.75      0.83      0.79       222
           4       0.89      0.37      0.52       111
           5       0.75      0.88      0.81       256
           6       0.00      0.00      0.00        23
           7       1.00      0.40      0.57        65
           8       0.00      0.00      0.00         7
           9       0.78      0.91      0.84       251
          10       0.87      0.52      0.65        25
          11       1.00      0.32      0.49        37
          12       0.80      0.38      0.51        53
          13       1.00      0.12      0.22         8
          14       1.00      0.43      0.61        23
          15       0.79      0.48      0.60        87
          16       0.00      0.00      0.00         6
          17       0.50    

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [136]:
#Q10
print(y_test1,y_predict)

[[0 1 0 ... 1 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 1 ... 1 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]] [[0 1 0 ... 1 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]
